Categories:
  - Writing
License: GPL-3.0-only
AuthorName: Tosin Onikute
AuthorEmail: tosinmath007@gmail.com
SourceCode: https://github.com/tosinonikute/NotelyVoice
IssueTracker: https://github.com/tosinonikute/NotelyVoice/issues
Changelog: https://github.com/tosinonikute/NotelyVoice/releases

AutoName: Notely Voice

RepoType: git
Repo: https://github.com/tosinonikute/NotelyVoice.git
Binaries: https://github.com/tosinonikute/NotelyVoice/releases/download/v%v/androidApp-release-v%v.apk

Builds:
  - versionName: 1.0.7
    versionCode: 8
    commit: ab225f4d2cbee4e43527f196d21bd8f566954fd0
    subdir: androidApp
    gradle:
      - yes
    prebuild: sed -i -e '/jetbrains/d' ../settings.gradle.kts

AllowedAPKSigningKeys: ebdd1d201b50253823b2d81dfb4806823728a388e58b52ff39e28b7add924cd5

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.0.7
CurrentVersionCode: 8
