archive:
  description: The archive of the official F-Droid Free Software repository. Apps here are old and can contain known vulnerabilities and security issues!
  name: F-Droid Archive
repo:
  description: The official F-Droid Free Software repository. Everything in this repository is always built from the source code.
  name: F-Droid
