name: F-Droid Build

on:
  push:
    branches:
      - master

jobs:
  fdroid:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitLab repo (public)
        run: git clone --depth=1 https://gitlab.com/Pentarctagon/fdroiddata ~/fdroiddata

      - name: Clone fdroidserver repo (shallow)
        run: git clone --depth=1 https://gitlab.com/fdroid/fdroidserver ~/fdroidserver

      - name: Install Deps
        run: sudo apt-get update

      - name: Fix config.yml permissions
        run: chmod 600 ${{ github.workspace }}/fdroiddata/config.yml

      - name: Run fdroid readmeta
        run: |
          docker run --rm -i \
            -v ${{ github.workspace }}/fdroiddata:/build:z \
            -v ~/fdroidserver:/home/vagrant/fdroidserver:Z \
            registry.gitlab.com/fdroid/fdroidserver:buildserver \
            /bin/bash -c '
              source /etc/profile
              export fdroidserver=/home/vagrant/fdroidserver
              export PATH="$fdroidserver:$PATH" PYTHONPATH="$fdroidserver"
              cd /build
              fdroid readmeta
            '

      - name: Run fdroid rewritemeta
        run: |
          docker run --rm -i \
            -v ${{ github.workspace }}/fdroiddata:/build:z \
            -v ~/fdroidserver:/home/vagrant/fdroidserver:Z \
            registry.gitlab.com/fdroid/fdroidserver:buildserver \
            /bin/bash -c '
              source /etc/profile
              export fdroidserver=/home/vagrant/fdroidserver
              export PATH="$fdroidserver:$PATH" PYTHONPATH="$fdroidserver"
              cd /build
              fdroid rewritemeta org.wesnoth.Wesnoth
            '

      - name: Run fdroid lint
        run: |
          docker run --rm -i \
            -v ${{ github.workspace }}/fdroiddata:/build:z \
            -v ~/fdroidserver:/home/vagrant/fdroidserver:Z \
            registry.gitlab.com/fdroid/fdroidserver:buildserver \
            /bin/bash -c '
              source /etc/profile
              export fdroidserver=/home/vagrant/fdroidserver
              export PATH="$fdroidserver:$PATH" PYTHONPATH="$fdroidserver"
              cd /build
              fdroid lint org.wesnoth.Wesnoth
            '

      - name: Run fdroid build
        run: |
          docker run --rm -i \
            -v ${{ github.workspace }}/fdroiddata:/build:z \
            -v ~/fdroidserver:/home/vagrant/fdroidserver:Z \
            registry.gitlab.com/fdroid/fdroidserver:buildserver \
            /bin/bash -c '
              ls -la /build/.git
              source /etc/profile
              export fdroidserver=/home/vagrant/fdroidserver
              export PATH="$fdroidserver:$PATH" PYTHONPATH="$fdroidserver"
              cd /build
              fdroid build --skip-git org.wesnoth.Wesnoth
            '
